"use client";

import { REPORT } from "@/lib/data/report";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FileText, AlertTriangle, TrendingUp, Trophy, ListChecks, Cpu } from "lucide-react";

const ICONS = [FileText, TrendingUp, AlertTriangle, AlertTriangle, ListChecks];

export function ReportView() {
  return (
    <div className="space-y-5">
      {/* Report header */}
      <Card className="overflow-hidden border-primary/20">
        <div className="bg-gradient-to-br from-primary/10 via-primary/5 to-transparent p-5">
          <div className="flex items-start gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-sm">
              <FileText className="h-5 w-5" />
            </div>
            <div className="flex-1">
              <h2 className="text-lg font-bold tracking-tight text-foreground">
                AI Support Agent for @AmazonHelp — Report
              </h2>
              <p className="mt-0.5 text-sm text-muted-foreground">
                Findings, baselines & failure analysis 
              </p>
              <div className="mt-2 flex flex-wrap gap-1.5">
                <Badge variant="secondary" className="text-[10px] gap-1">
                  <Cpu className="h-2.5 w-2.5" />
                  Powered by zai-llm-v1
                </Badge>
                <Badge variant="secondary" className="text-[10px]">Intent classification</Badge>
                <Badge variant="secondary" className="text-[10px]">Grounded reply drafting</Badge>
                <Badge variant="secondary" className="text-[10px]">Hybrid escalation</Badge>
                <Badge variant="secondary" className="text-[10px]">Fine-tuned sentiment</Badge>
                <Badge variant="secondary" className="text-[10px]">LLM-as-judge</Badge>
              </div>
            </div>
          </div>
        </div>
      </Card>

      {/* Sections */}
      <div className="space-y-4">
        {REPORT.map((section, idx) => {
          const Icon = ICONS[idx] ?? FileText;
          return (
            <Card key={section.id}>
              <CardHeader className="pb-2">
                <CardTitle className="flex items-center gap-2 text-sm">
                  <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <Icon className="h-3.5 w-3.5" />
                  </div>
                  {section.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {section.body.map((para, i) => (
                  <p key={i} className="text-sm leading-relaxed text-foreground/85">
                    {para}
                  </p>
                ))}
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Closing note */}
      <Card className="border-dashed">
        <CardContent className="flex items-start gap-3 p-4">
          <Trophy className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
          <div>
            <div className="text-sm font-semibold text-foreground">
              The proof is worth more than the system
            </div>
            <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
              This report, the evaluation harness, the golden set, and the decision log together constitute the evidence
              that the agent is good enough to trust. The live Playground lets you reproduce any single result in seconds.
              Intent classification, reply drafting, escalation decisions, and LLM-based sentiment are generated by the{" "}
              <span className="font-medium text-foreground">GLM-4-Plus</span> model via the z-ai-web-dev-sdk.
              A fine-tuned BERT sentiment model (<span className="font-medium text-foreground">bert-novel-v1</span>) is also
              integrated for side-by-side sentiment comparison, hosted at jyqti-bert-novel.hf.space.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
